apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-downloader-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/youtube-downloads"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-downloader-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: youtube-downloader-pv
