apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-downloader-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /root/Downloads
