apiVersion: v1
kind: PersistentVolume
metadata:
  name: youtube-downloader-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/root/Downloads"

